pip install pytest
pip install selenium
pip install webdriver-manager
pip install pytest-html
pip install pytest-xdist
pip install openpyxl
pip install allure-pytest
pip install webdriverdownloader
pip install pytest-ordering
pip install pytest-metadata
pip install pytest-dependency
pip install py-parser
pip install requests